/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { EduTrustRegistry } from './EduTrustRegistry.js';
export * as factories from './factories/index.js';
export { EduTrustRegistry__factory } from './factories/EduTrustRegistry__factory.js';